language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg

script:
    - wget https://transfer.sh/3uC8Dc/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $user $pass
    #Massive
    - mega-get https://mega.nz/file/1rRQxDwA#nqDtvmqfxGsrlp9eEOjXdk_k_Ht8zvUgi8HzkpZbPk8 aCapitulo_047.mp4
    - mega-get https://mega.nz/file/B3BgzBJI#HT_Sp680QZ06wCrJivch7-qBg_rP84YlzE5YF16fYlY aCapitulo_047.srt
    - ffmpeg -i aCapitulo_047.mp4 -i aCapitulo_047.srt -c copy -c:s mov_text Capitulo_047.mp4
    - travis_wait 20 curl -T Capitulo_047.mp4 https://transfer.sh/Capitulo_047.mp4
    - mega-get https://mega.nz/file/0qYGmTbY#Xw04e2iZI_HNsgSrpNlD3mWvGWq0n5kKVO4PH-9H6mI aCapitulo_048.mp4
    - mega-get https://mega.nz/file/dmYChDTK#7ETDOcd3vM51xXzlIbdzGe3dDn09FjkKBq4xDBbA548 aCapitulo_048.srt
    - ffmpeg -i aCapitulo_048.mp4 -i aCapitulo_048.srt -c copy -c:s mov_text Capitulo_048.mp4
    - travis_wait 20 curl -T Capitulo_048.mp4 https://transfer.sh/Capitulo_048.mp4
    - mega-get https://mega.nz/file/A2YkADrK#g1l9DPxeVBDuAB3k5cBHV7rHkCP7GmcXsD8PWcYIUBM aCapitulo_056.mp4
    - mega-get https://mega.nz/file/tvQGwDLZ#fd01YvjCMg6eqKnjbSAaHbGQjSBB1B4ZBkWwhiDfj6I aCapitulo_056.srt
    - ffmpeg -i aCapitulo_056.mp4 -i aCapitulo_056.srt -c copy -c:s mov_text Capitulo_056.mp4
    - travis_wait 20 curl -T Capitulo_056.mp4 https://transfer.sh/Capitulo_056.mp4
    - mega-get https://mega.nz/file/p2RSgDiJ#Dxk4jtOlapL-XE0OTLPupFB62kTeHBZm1Mw9JVJtXQw aCapitulo_057.mp4
    - mega-get https://mega.nz/file/UyRywD7J#XtKJ4PO3u4zeAU6gRjnbXiaL_4kuB5hCqsjbaKxB67o aCapitulo_057.srt
    - ffmpeg -i aCapitulo_057.mp4 -i aCapitulo_057.srt -c copy -c:s mov_text Capitulo_057.mp4
    - travis_wait 20 curl -T Capitulo_057.mp4 https://transfer.sh/Capitulo_057.mp4
    - mega-get https://mega.nz/file/BzYU2TAZ#Dla1JEvSlCAAQBZgNKY5RLWhp_gVupTR9NzX0Ccjjew aCapitulo_058.mp4
    - mega-get https://mega.nz/file/s2YGhbhS#s-LmSHQDMT4iM0NV8N5u61kCmU_UAKd565V7WNHSbBg aCapitulo_058.srt
    - ffmpeg -i aCapitulo_058.mp4 -i aCapitulo_058.srt -c copy -c:s mov_text Capitulo_058.mp4
    - travis_wait 20 curl -T Capitulo_058.mp4 https://transfer.sh/Capitulo_058.mp4
    - mega-get https://mega.nz/file/s6AmlZwT#Cd7p7szAgNyGwQH_S7OwfdNJ-uEAhhMAcwMGAsJT1TM aCapitulo_059.mp4
    - mega-get https://mega.nz/file/EmYCWZrB#TzUNOAyRn8LzrOPKuiQ3WcrydDh9Kl5BcAqACckh35E aCapitulo_059.srt
    - ffmpeg -i aCapitulo_059.mp4 -i aCapitulo_059.srt -c copy -c:s mov_text Capitulo_059.mp4
    - travis_wait 20 curl -T Capitulo_059.mp4 https://transfer.sh/Capitulo_059.mp4
    - mega-get https://mega.nz/file/QuRCUDqJ#AsI2r1673UplhdQx6VZRQFc08MTrcOGNcf-e7AOzUtM aCapitulo_062.mp4
    - mega-get https://mega.nz/file/w7J2CbrL#-S5CguZVJVYZre0Xvy9khxJ9O4XldS2QRKr8kY9-E5s aCapitulo_062.srt
    - ffmpeg -i aCapitulo_062.mp4 -i aCapitulo_062.srt -c copy -c:s mov_text Capitulo_062.mp4
    - travis_wait 20 curl -T Capitulo_062.mp4 https://transfer.sh/Capitulo_062.mp4
    - mega-get https://mega.nz/file/1qRGkZgY#5t_RJ2psTEFR227BUpDkZz96OUunuJ3RZyE4vWk3W-4 aCapitulo_065.mp4
    - mega-get https://mega.nz/file/MiREwRRA#QmhdvOo6IhIKAUN1mfc75mZnKh4UKRmx_XMKPcnI2To aCapitulo_065.srt
    - ffmpeg -i aCapitulo_065.mp4 -i aCapitulo_065.srt -c copy -c:s mov_text Capitulo_065.mp4
    - travis_wait 20 curl -T Capitulo_065.mp4 https://transfer.sh/Capitulo_065.mp4
    - mega-get https://mega.nz/file/szYQWbxQ#gJKejSYa603lggj2heIe02LAmiOSw0EOLKP26FnAffs aCapitulo_066.mp4
    - mega-get https://mega.nz/file/YnQ2HLZD#c_qhHnb4XcPuaMl6cciWB1DnKOS8sTwr0e5jtPjsUN8 aCapitulo_066.srt
    - ffmpeg -i aCapitulo_066.mp4 -i aCapitulo_066.srt -c copy -c:s mov_text Capitulo_066.mp4
    - travis_wait 20 curl -T Capitulo_066.mp4 https://transfer.sh/Capitulo_066.mp4
    - mega-get https://mega.nz/file/tvZkhLLC#3XQymspB_GNSnGwcErPEKNuh13cPIU5ck7aHkYoO40o aCapitulo_067.mp4
    - mega-get https://mega.nz/file/kqJygBJC#NTU2PyRgtUhUEP-sLEFl-M5LYkaMcytgxIA95JhHjik aCapitulo_067.srt
    - ffmpeg -i aCapitulo_067.mp4 -i aCapitulo_067.srt -c copy -c:s mov_text Capitulo_067.mp4
    - travis_wait 20 curl -T Capitulo_067.mp4 https://transfer.sh/Capitulo_067.mp4
    - mega-get https://mega.nz/file/tyQSCZDJ#ZXK1cVUjj20Jhpl1U9cG5oeZx12ZU_OBZh220Td_uW4 aCapitulo_068.mp4
    - mega-get https://mega.nz/file/lqQSlDZa#pjoSV4UdcH4A0Hjuyfn1M8-5xrfypYJBqvvY8JnYp6I aCapitulo_068.srt
    - ffmpeg -i aCapitulo_068.mp4 -i aCapitulo_068.srt -c copy -c:s mov_text Capitulo_068.mp4
    - travis_wait 20 curl -T Capitulo_068.mp4 https://transfer.sh/Capitulo_068.mp4
