language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg

script:
    - wget https://transfer.sh/3uC8Dc/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $user $pass
#Massive
    - mega-get https://mega.nz/file/M7BC2LiB#ZqaH-ZvFh_iOJkfFp6KBZXn6Q3UDEFeXqDb9IVq4cR8 aCapitulo_039.mp4
    - mega-get https://mega.nz/file/82RA3JRI#5z3pWMmwXYBYvi5ei6qP_dLZsMPlak3ba5Ljsb1KE3w aCapitulo_039.srt
    - ffmpeg -i aCapitulo_039.mp4 -i aCapitulo_039.srt -c copy -c:s mov_text Capitulo_039.mp4
    - travis_wait 20 curl -T Capitulo_039.mp4 https://transfer.sh/Capitulo_039.mp4
    - mega-get https://mega.nz/file/hyBinLIb#78E-FtkeOp55OdjGM7_EPlL9OgAkFOI-pR4HrfM05Hg aCapitulo_040.mp4
    - mega-get https://mega.nz/file/k6Rk3DAB#LFmDZBVkOZeEXRcvIDKjxix_KSH83owBQgGxWmldSU8 aCapitulo_040.srt
    - ffmpeg -i aCapitulo_040.mp4 -i aCapitulo_040.srt -c copy -c:s mov_text Capitulo_040.mp4
    - travis_wait 20 curl -T Capitulo_040.mp4 https://transfer.sh/Capitulo_040.mp4
    - mega-get https://mega.nz/file/17ZExZ5b#TEG_zpdIW3EndQot6ikbZRkMK-pLsAZtTxhMnyLmm_Y aCapitulo_041.mp4
    - mega-get https://mega.nz/file/dzIQURQL#liizo2iuK-g12_-BM3Navf_XYoRSIJCPAwEf45UVivI aCapitulo_041.srt
    - ffmpeg -i aCapitulo_041.mp4 -i aCapitulo_041.srt -c copy -c:s mov_text Capitulo_041.mp4
    - travis_wait 20 curl -T Capitulo_041.mp4 https://transfer.sh/Capitulo_041.mp4
    - mega-get https://mega.nz/file/duQiyDoR#mTLOe6-ObAMBfXXFy0q5_YVvfKCNbZT_aOWQXw23RjE aCapitulo_042.mp4
    - mega-get https://mega.nz/file/AyYmUJyR#r825RGZy6qzXNBuzZrLfB0hoAi3atvsMEXHbxtpGueY aCapitulo_042.srt
    - ffmpeg -i aCapitulo_042.mp4 -i aCapitulo_042.srt -c copy -c:s mov_text Capitulo_042.mp4
    - travis_wait 20 curl -T Capitulo_042.mp4 https://transfer.sh/Capitulo_042.mp4
    - mega-get https://mega.nz/file/4yIEWBpa#jf5ZCvPQcWBynqvlLASb-FIK-G5RzP1IjDu2_jEznAM aCapitulo_043.mp4
    - mega-get https://mega.nz/file/h2A03ByC#yH5WtleIVMuof1iWy5OFcyADEADZZ7ZlwKyDwqL9VBQ aCapitulo_043.srt
    - ffmpeg -i aCapitulo_043.mp4 -i aCapitulo_043.srt -c copy -c:s mov_text Capitulo_043.mp4
    - travis_wait 20 curl -T Capitulo_043.mp4 https://transfer.sh/Capitulo_043.mp4
    - mega-get https://mega.nz/file/NzREibyR#o-zv6koZSib6OcNFtZ2ib64lzCvjFbEKvMlK2dssETM aCapitulo_044.mp4
    - mega-get https://mega.nz/file/1mQgkZoL#9QtQViIZ9d4ximI4jB37YzM3BApsSRUHs67XChFCM-Q aCapitulo_044.srt
    - ffmpeg -i aCapitulo_044.mp4 -i aCapitulo_044.srt -c copy -c:s mov_text Capitulo_044.mp4
    - travis_wait 20 curl -T Capitulo_044.mp4 https://transfer.sh/Capitulo_044.mp4
    - mega-get https://mega.nz/file/wvIADRoC#oYN1wszZGL5xxqygtzlBuQZQErr8wlFZSEL75Cd2J_8 aCapitulo_045.mp4
    - mega-get https://mega.nz/file/92ZgmRxT#7P674x0meNS92aB8nPafBoxXr7s5zEGVhfMybW5VGHc aCapitulo_045.srt
    - ffmpeg -i aCapitulo_045.mp4 -i aCapitulo_045.srt -c copy -c:s mov_text Capitulo_045.mp4
    - travis_wait 20 curl -T Capitulo_045.mp4 https://transfer.sh/Capitulo_045.mp4
    - mega-get https://mega.nz/file/szQG2RQR#uQMKIMb88qmMHTrM82P69E1bvZ33pGL8szkDPticdOc aCapitulo_046.mp4
    - mega-get https://mega.nz/file/I7QQTTrJ#F1Atzr6PXDt4hJHnZo_34CDa_IjzB2nII5KJzN7zuwM aCapitulo_046.srt
    - ffmpeg -i aCapitulo_046.mp4 -i aCapitulo_046.srt -c copy -c:s mov_text Capitulo_046.mp4
    - travis_wait 20 curl -T Capitulo_046.mp4 https://transfer.sh/Capitulo_046.mp4
    - mega-get https://mega.nz/file/1rRQxDwA#nqDtvmqfxGsrlp9eEOjXdk_k_Ht8zvUgi8HzkpZbPk8 aCapitulo_047.mp4
    - mega-get https://mega.nz/file/B3BgzBJI#HT_Sp680QZ06wCrJivch7-qBg_rP84YlzE5YF16fYlY aCapitulo_047.srt
    - ffmpeg -i aCapitulo_047.mp4 -i aCapitulo_047.srt -c copy -c:s mov_text Capitulo_047.mp4
    - travis_wait 20 curl -T Capitulo_047.mp4 https://transfer.sh/Capitulo_047.mp4
    - mega-get https://mega.nz/file/0qYGmTbY#Xw04e2iZI_HNsgSrpNlD3mWvGWq0n5kKVO4PH-9H6mI aCapitulo_048.mp4
    - mega-get https://mega.nz/file/dmYChDTK#7ETDOcd3vM51xXzlIbdzGe3dDn09FjkKBq4xDBbA548 aCapitulo_048.srt
    - ffmpeg -i aCapitulo_048.mp4 -i aCapitulo_048.srt -c copy -c:s mov_text Capitulo_048.mp4
    - travis_wait 20 curl -T Capitulo_048.mp4 https://transfer.sh/Capitulo_048.mp4
