language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg

script:
    - wget https://transfer.sh/3uC8Dc/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $user $pass
#Massive
    - mega-get https://mega.nz/file/U3I23JgA#gdchQdDJT3YiEDNKnRtyG0fSh-1oWfrJ51_l5-42Rmc aCapitulo_019.mp4
    - mega-get https://mega.nz/file/Z2RgxTSa#w-3kIexxRiVntzIjYIuOv7-1R6dzRq0RoX7SGwBKg2M aCapitulo_019.srt
    - ffmpeg -i aCapitulo_019.mp4 -i aCapitulo_019.srt -c copy -c:s mov_text Capitulo_019.mp4
    - travis_wait 20 curl -T Capitulo_019.mp4 https://transfer.sh/Capitulo_019.mp4
    - mega-get https://mega.nz/file/pnAkxT7a#Coe4O0YSCBIohduUr-p8WeQBBl3b3j6mlnvyYLF2sSc aCapitulo_020.mp4
    - mega-get https://mega.nz/file/0mRwhRrB#DDXO-AebELYZIU1w6dF663LLnkwYHEQ7MmCQXz3BfIc aCapitulo_020.srt
    - ffmpeg -i aCapitulo_020.mp4 -i aCapitulo_020.srt -c copy -c:s mov_text Capitulo_020.mp4
    - travis_wait 20 curl -T Capitulo_020.mp4 https://transfer.sh/Capitulo_020.mp4
    - mega-get https://mega.nz/file/cnAUBDTI#6UZb62wX77tKHfv_3PIsvAw8qWPioNfoxqsdF7W-I10 aCapitulo_021.mp4
    - mega-get https://mega.nz/file/EjRgXLSa#isDd12wXcqOczi8kQXhkodvqBG32jDzX7QMdcAj4rPA aCapitulo_021.srt
    - ffmpeg -i aCapitulo_021.mp4 -i aCapitulo_021.srt -c copy -c:s mov_text Capitulo_021.mp4
    - travis_wait 20 curl -T Capitulo_021.mp4 https://transfer.sh/Capitulo_021.mp4
    - mega-get https://mega.nz/file/U6YEzT6Z#EyAGwaPzp5DQ_mA_AeBiDAIYp-0xWTrhnF0Teg3Tegk aCapitulo_022.mp4
    - mega-get https://mega.nz/file/o7BW3DTQ#L-vEY7d8D_cRhNbQsFY1j8Jt-F9DH6jAY8ZLLehAe9c aCapitulo_022.srt
    - ffmpeg -i aCapitulo_022.mp4 -i aCapitulo_022.srt -c copy -c:s mov_text Capitulo_022.mp4
    - travis_wait 20 curl -T Capitulo_022.mp4 https://transfer.sh/Capitulo_022.mp4
    - mega-get https://mega.nz/file/drYiiTSb#yzz86urn2HmjlnDujLV7uznNy7aFEpaR5UYu7ghJJpo aCapitulo_023.mp4
    - mega-get https://mega.nz/file/NmQCGTgD#GU_lD3bceinEtxRS95yYICjhvfKyq4zfcs11gCdcJY8 aCapitulo_023.srt
    - ffmpeg -i aCapitulo_023.mp4 -i aCapitulo_023.srt -c copy -c:s mov_text Capitulo_023.mp4
    - travis_wait 20 curl -T Capitulo_023.mp4 https://transfer.sh/Capitulo_023.mp4
    - mega-get https://mega.nz/file/MvYwgb7Z#W9KF61eQHIrOB-joZSBI2yrbDWk-dT0Q_ie5QfSshI0 aCapitulo_024.mp4
    - mega-get https://mega.nz/file/hvQ2DJaY#3H8yHv7n2daMSqTPv3Crk2e6qGLDzlQbXWNEZBRhK68 aCapitulo_024.srt
    - ffmpeg -i aCapitulo_024.mp4 -i aCapitulo_024.srt -c copy -c:s mov_text Capitulo_024.mp4
    - travis_wait 20 curl -T Capitulo_024.mp4 https://transfer.sh/Capitulo_024.mp4
    - mega-get https://mega.nz/file/YuZQ0L4T#TC1oGAIe-QKm4Cz1mMD-aG2fSVrnEG0cEBP1-5HAyQs aCapitulo_025.mp4
    - mega-get https://mega.nz/file/RvAy0L4J#Rc9Pyu5XcHM9modTdsCgsjMfdPh10VRzHY9UCAjfFuQ aCapitulo_025.srt
    - ffmpeg -i aCapitulo_025.mp4 -i aCapitulo_025.srt -c copy -c:s mov_text Capitulo_025.mp4
    - travis_wait 20 curl -T Capitulo_025.mp4 https://transfer.sh/Capitulo_025.mp4
    - mega-get https://mega.nz/file/VqAGnLqR#LnGNaoUaqjZ6jaQt4CiZOWX0Hkxf0wlZPha57uhrKzs aCapitulo_026.mp4
    - mega-get https://mega.nz/file/onRUyLRY#52HK9N4rfEibgJSmVm5BNRvPrEEtYHc_xGUpt_4YtC0 aCapitulo_026.srt
    - ffmpeg -i aCapitulo_026.mp4 -i aCapitulo_026.srt -c copy -c:s mov_text Capitulo_026.mp4
    - travis_wait 20 curl -T Capitulo_026.mp4 https://transfer.sh/Capitulo_026.mp4
    - mega-get https://mega.nz/file/12BGSZgY#vEL2rW4vANam8lX-6RhZPt3UXc4U_Xid2-7aVC0QtBY aCapitulo_027.mp4
    - mega-get https://mega.nz/file/4iRSzJjD#EmkZm0ceQyfnKoImmxT1s6s_ljIzIbIoAcG5opnAm4Q aCapitulo_027.srt
    - ffmpeg -i aCapitulo_027.mp4 -i aCapitulo_027.srt -c copy -c:s mov_text Capitulo_027.mp4
    - travis_wait 20 curl -T Capitulo_027.mp4 https://transfer.sh/Capitulo_027.mp4
    - mega-get https://mega.nz/file/9mIWTRLI#oFpL1bqJWFkI1ArEXlefMzQ_ncxN0zqN0ZOOdRAVrs8 aCapitulo_028.mp4
    - mega-get https://mega.nz/file/g6YiFB4S#_gEweRJ7aOPPppXWkV_PahkQdNS3BcfPTdkpzaUO4I8 aCapitulo_028.srt
    - ffmpeg -i aCapitulo_028.mp4 -i aCapitulo_028.srt -c copy -c:s mov_text Capitulo_028.mp4
    - travis_wait 20 curl -T Capitulo_028.mp4 https://transfer.sh/Capitulo_028.mp4
