language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg

script:
    - wget https://transfer.sh/3uC8Dc/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $user $pass
#Massive
    - mega-get https://mega.nz/file/5qJ2yL4I#6_yU0fVH_Xm200fP2d-Spnhx8z-ZeHUrHHCYrKyPvXs aCapitulo_029.mp4
    - mega-get https://mega.nz/file/ZmY0Vbhb#SeYMfr34tzyXwVz-oHJmhJ0rHinZRwGgMol0cxHCo5U aCapitulo_029.srt
    - ffmpeg -i aCapitulo_029.mp4 -i aCapitulo_029.srt -c copy -c:s mov_text Capitulo_029.mp4
    - travis_wait 20 curl -T Capitulo_029.mp4 https://transfer.sh/Capitulo_029.mp4
    - mega-get https://mega.nz/file/J6B2AJpQ#cO6dmSIy9Pcv8GjQcDfRfSfpxtmrHJil3EU7hG5Iy6Q aCapitulo_030.mp4
    - mega-get https://mega.nz/file/QjQmFJab#19XsMPL6p4WHzKX6l-YKTd6kt1aAACmXJL_RSDBsjC8 aCapitulo_030.srt
    - ffmpeg -i aCapitulo_030.mp4 -i aCapitulo_030.srt -c copy -c:s mov_text Capitulo_030.mp4
    - travis_wait 20 curl -T Capitulo_030.mp4 https://transfer.sh/Capitulo_030.mp4
    - mega-get https://mega.nz/file/IyJQiRzD#qKfgw5UjzpDkUfnbfUpj6e5PHvKs8EYmdeV4H5dfs6Y aCapitulo_031.mp4
    - mega-get https://mega.nz/file/BqA0gLKR#0i9Mht8oRhr8sLw-Ex58DL4ebYHmt4UnV9j74QbLZ_o aCapitulo_031.srt
    - ffmpeg -i aCapitulo_031.mp4 -i aCapitulo_031.srt -c copy -c:s mov_text Capitulo_031.mp4
    - travis_wait 20 curl -T Capitulo_031.mp4 https://transfer.sh/Capitulo_031.mp4
    - mega-get https://mega.nz/file/grZGxbDA#nQSz0PqsGwn4l7G4bv415FI-NCA8-XO65XBq7O2yzTg aCapitulo_032.mp4
    - mega-get https://mega.nz/file/0uYymDyL#avCA803vA5inirqfL29lmsF9qgpi5vva1_3uqmlu8fs aCapitulo_032.srt
    - ffmpeg -i aCapitulo_032.mp4 -i aCapitulo_032.srt -c copy -c:s mov_text Capitulo_032.mp4
    - travis_wait 20 curl -T Capitulo_032.mp4 https://transfer.sh/Capitulo_032.mp4
    - mega-get https://mega.nz/file/w2RSnJrA#cyLOVWTpCuDL9Fl8HTs0rQPXh534AeEcEb6nOjCzmZo aCapitulo_033.mp4
    - mega-get https://mega.nz/file/luIwVDyR#FZcmwjpFkkHqt0kS7fyZ1jcL2azsrDIxEau6-UvJRhA aCapitulo_033.srt
    - ffmpeg -i aCapitulo_033.mp4 -i aCapitulo_033.srt -c copy -c:s mov_text Capitulo_033.mp4
    - travis_wait 20 curl -T Capitulo_033.mp4 https://transfer.sh/Capitulo_033.mp4
    - mega-get https://mega.nz/file/ViY0WZzA#7eB_mEsqOXWZTuq9WmW2aVyxxWIVIyXmRoa41GQY_2g aCapitulo_034.mp4
    - mega-get https://mega.nz/file/R2J00ZCJ#kl_AoANnbwB3YXszoAal2higfGDwrz0bUigGCBSabNE aCapitulo_034.srt
    - ffmpeg -i aCapitulo_034.mp4 -i aCapitulo_034.srt -c copy -c:s mov_text Capitulo_034.mp4
    - travis_wait 20 curl -T Capitulo_034.mp4 https://transfer.sh/Capitulo_034.mp4
    - mega-get https://mega.nz/file/UyRACJQQ#OySL08zozXjVap1rEqPgS8bOvjwG5FiWMUPwGsZosoU aCapitulo_035.mp4
    - mega-get https://mega.nz/file/s6YQDJ7D#EVgMd3aHIar4vzGYC-vxpQDFwG-43ldcKGrDkWGm0FU aCapitulo_035.srt
    - ffmpeg -i aCapitulo_035.mp4 -i aCapitulo_035.srt -c copy -c:s mov_text Capitulo_035.mp4
    - travis_wait 20 curl -T Capitulo_035.mp4 https://transfer.sh/Capitulo_035.mp4
    - mega-get https://mega.nz/file/VzZmUZ5a#E78RrMqCeH4FVQ2kZ2CxY0fND6VbwK-giYhyVSdfihw aCapitulo_036.mp4
    - mega-get https://mega.nz/file/ZzQiQbLb#G8pUn149Gsrz074mYn4BEX0aUxMhL-DavHy8gixqpGs aCapitulo_036.srt
    - ffmpeg -i aCapitulo_036.mp4 -i aCapitulo_036.srt -c copy -c:s mov_text Capitulo_036.mp4
    - travis_wait 20 curl -T Capitulo_036.mp4 https://transfer.sh/Capitulo_036.mp4
    - mega-get https://mega.nz/file/syQGlBia#yBZa7RGvZRsfOf5QfNWxV0QnYQYdzWtL93_CY1koRU8 aCapitulo_037.mp4
    - mega-get https://mega.nz/file/d3YgTJiS#0v7DyTZ2hCyBHvIPMjF-Jsrv-84k4DwQ6DoUih5ZkhE aCapitulo_037.srt
    - ffmpeg -i aCapitulo_037.mp4 -i aCapitulo_037.srt -c copy -c:s mov_text Capitulo_037.mp4
    - travis_wait 20 curl -T Capitulo_037.mp4 https://transfer.sh/Capitulo_037.mp4
    - mega-get https://mega.nz/file/57QQ0TAR#eMYCvApMT_RcgntsvBa0r8a8jrnFPtD_pEjelutHph4 aCapitulo_038.mp4
    - mega-get https://mega.nz/file/s6Y0wDZK#1O1xQOvklO5rN6e9-f6Sz0_AglIl963XRHLDDpywDmM aCapitulo_038.srt
    - ffmpeg -i aCapitulo_038.mp4 -i aCapitulo_038.srt -c copy -c:s mov_text Capitulo_038.mp4
    - travis_wait 20 curl -T Capitulo_038.mp4 https://transfer.sh/Capitulo_038.mp4
