language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg

script:
    - wget https://transfer.sh/3uC8Dc/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $user $pass
#Massive
    - mega-get https://mega.nz/file/lrQSSbIY#0XCwyG8JYig3ThiCOnDTZnP4wdILGBa7e_5oHt6Z_Vk aCapitulo_069.mp4
    - mega-get https://mega.nz/file/kzRUABAQ#-iJ-pHaubt5FdGsHh0yJjkR4Ozk5tV6GK3qb7mfq-HE aCapitulo_069.srt
    - ffmpeg -i aCapitulo_069.mp4 -i aCapitulo_069.srt -c copy -c:s mov_text Capitulo_069.mp4
    - travis_wait 20 curl -T Capitulo_069.mp4 https://transfer.sh/Capitulo_069.mp4
    - mega-get https://mega.nz/file/ciAQzZzQ#ivk5VjS8iG3vkM2jafEyu7xXJDAQNNjvDq1RPPMTzck aCapitulo_070.mp4
    - mega-get https://mega.nz/file/czYQ0bwY#SLD19Y3p5Wg-eHqzwYmSOffE2z2E-hcEyQH1d5PfuBE aCapitulo_070.srt
    - ffmpeg -i aCapitulo_070.mp4 -i aCapitulo_070.srt -c copy -c:s mov_text Capitulo_070.mp4
    - travis_wait 20 curl -T Capitulo_070.mp4 https://transfer.sh/Capitulo_070.mp4
    - mega-get https://mega.nz/file/lqYGnbaQ#OAyhIasW59No-fSa_7TtZy6c8cQx3fwrv7CO-QjJFNg aCapitulo_071.mp4
    - mega-get https://mega.nz/file/8jZG0JTD#fl2JVkvVlJJx5z-dyKBaz7UViQs5KyMclBBNN0pRzkk aCapitulo_071.srt
    - ffmpeg -i aCapitulo_071.mp4 -i aCapitulo_071.srt -c copy -c:s mov_text Capitulo_071.mp4
    - travis_wait 20 curl -T Capitulo_071.mp4 https://transfer.sh/Capitulo_071.mp4
    - mega-get https://mega.nz/file/p7JEQLyK#-T_wTeBqZylWWo0s99oJ8IHxvC-RehvC7BfYuWKnYPQ aCapitulo_072.mp4
    - mega-get https://mega.nz/file/cmByHLrD#Fo1CYbJJWm5Llvt0mM_VfJzot0h76ZzXPewzcSJBMes aCapitulo_072.srt
    - ffmpeg -i aCapitulo_072.mp4 -i aCapitulo_072.srt -c copy -c:s mov_text Capitulo_072.mp4
    - travis_wait 20 curl -T Capitulo_072.mp4 https://transfer.sh/Capitulo_072.mp4
    - mega-get https://mega.nz/file/wvZghLBI#vYh-hhoHmPFKF0qp8l713QXCvP0mONXLpPIeZgDrZbE aCapitulo_073.mp4
    - mega-get https://mega.nz/file/J6JwBBDT#YHEfjyXvxp70Kf8wo-qnOfIm-aGYBum80eUed2ktg9M aCapitulo_073.srt
    - ffmpeg -i aCapitulo_073.mp4 -i aCapitulo_073.srt -c copy -c:s mov_text Capitulo_073.mp4
    - travis_wait 20 curl -T Capitulo_073.mp4 https://transfer.sh/Capitulo_073.mp4
    - mega-get https://mega.nz/file/QnZiFbpZ#XtxtMKJYYI6kOu5TjJMJumxaPt-o03t6rAEVuDG8vxQ aCapitulo_074.mp4
    - mega-get https://mega.nz/file/k7ZSyTyL#2kpodGt0_HZ0AkMOMaGfKYLuJQCJYXWQUlkNiYaD5yM aCapitulo_074.srt
    - ffmpeg -i aCapitulo_074.mp4 -i aCapitulo_074.srt -c copy -c:s mov_text Capitulo_074.mp4
    - travis_wait 20 curl -T Capitulo_074.mp4 https://transfer.sh/Capitulo_074.mp4
    - mega-get https://mega.nz/file/wjIi2JpY#gm9rH7QBvGV9RFZrnKfaZplPGiJ0bI6efcISlRr_zj8 aCapitulo_075.mp4
    - mega-get https://mega.nz/file/BmZCWRDL#eC8d_Wl3ZTUp2gCUKb_7si-rqXw3ZTuuMKJ08uGk5gg aCapitulo_075.srt
    - ffmpeg -i aCapitulo_075.mp4 -i aCapitulo_075.srt -c copy -c:s mov_text Capitulo_075.mp4
    - travis_wait 20 curl -T Capitulo_075.mp4 https://transfer.sh/Capitulo_075.mp4
    - mega-get https://mega.nz/file/16BymRyI#RohL_pgVtUjH1VhnMu7sSmflxjJ2Fa7qGTs7Sulk_E0 aCapitulo_076.mp4
    - mega-get https://mega.nz/file/VmBWTZAY#7fytcu4-WKXlOjRYZhB0LTXTu8w3vaYg-sI6SKRuwQE aCapitulo_076.srt
    - ffmpeg -i aCapitulo_076.mp4 -i aCapitulo_076.srt -c copy -c:s mov_text Capitulo_076.mp4
    - travis_wait 20 curl -T Capitulo_076.mp4 https://transfer.sh/Capitulo_076.mp4
    - mega-get https://mega.nz/file/l3A0SRzK#EjlY1Bf_DRbB-ws9Ns865LQWvfeO1MktTKrSJRwKNRs aCapitulo_077.mp4
    - mega-get https://mega.nz/file/06Y2hZJI#d7-X8V4OJXcaWDLNfDD9SlxnHDDHWF7UUJBGfCyWYAI aCapitulo_077.srt
    - ffmpeg -i aCapitulo_077.mp4 -i aCapitulo_077.srt -c copy -c:s mov_text Capitulo_077.mp4
    - travis_wait 20 curl -T Capitulo_077.mp4 https://transfer.sh/Capitulo_077.mp4
    - mega-get https://mega.nz/file/AvIS2Bbb#nrh_AvFQkdD4zlzHwxfdAgk0FSLSWl7e9BXW7H0RoWs aCapitulo_078.mp4
    - mega-get https://mega.nz/file/1zJSRBbA#y9kT81FvYg9F5FcZzTtjC7mOrcik9t_7RZjll-OL7tU aCapitulo_078.srt
    - ffmpeg -i aCapitulo_078.mp4 -i aCapitulo_078.srt -c copy -c:s mov_text Capitulo_078.mp4
    - travis_wait 20 curl -T Capitulo_078.mp4 https://transfer.sh/Capitulo_078.mp4
