language: shell
os: linux
dist: bionic

addons:
  apt:
    packages:
    - libc-ares2
    - libcrypto++6
    - mediainfo
    - libmediainfo0v5
    - libzen0v5
    - ffmpeg

script:
    - wget https://transfer.sh/3uC8Dc/megacmd.deb
    - sudo dpkg -i megacmd.deb
    - mega-login $user $pass
#Massive
    - mega-get https://mega.nz/file/s6AmlZwT#Cd7p7szAgNyGwQH_S7OwfdNJ-uEAhhMAcwMGAsJT1TM aCapitulo_059.mp4
    - mega-get https://mega.nz/file/EmYCWZrB#TzUNOAyRn8LzrOPKuiQ3WcrydDh9Kl5BcAqACckh35E aCapitulo_059.srt
    - ffmpeg -i aCapitulo_059.mp4 -i aCapitulo_059.srt -c copy -c:s mov_text Capitulo_059.mp4
    - travis_wait 20 curl -T Capitulo_059.mp4 https://transfer.sh/Capitulo_059.mp4
    - mega-get https://mega.nz/file/AjJ2UbLD#vwVcgLQF9pcH-tTUBvBfdgKSKQQesnOPlf8mxGOrZUo aCapitulo_060.mp4
    - mega-get https://mega.nz/file/5yAyhbrJ#LTUGONMehCCoAS20WPjZo3lYOxFKvW6550qEV4Qr7r8 aCapitulo_060.srt
    - ffmpeg -i aCapitulo_060.mp4 -i aCapitulo_060.srt -c copy -c:s mov_text Capitulo_060.mp4
    - travis_wait 20 curl -T Capitulo_060.mp4 https://transfer.sh/Capitulo_060.mp4
    - mega-get https://mega.nz/file/xzJUWZyI#_sgDZ-E7Qvdcoj07F--Ofw7eF3goSF5GYva3AC3B9j4 aCapitulo_061.mp4
    - mega-get https://mega.nz/file/cjZmXLhJ#okQtxjCwDX2UwCprCBi3fbuk8w-gwI0QFGObbwYxBAw aCapitulo_061.srt
    - ffmpeg -i aCapitulo_061.mp4 -i aCapitulo_061.srt -c copy -c:s mov_text Capitulo_061.mp4
    - travis_wait 20 curl -T Capitulo_061.mp4 https://transfer.sh/Capitulo_061.mp4
    - mega-get https://mega.nz/file/QuRCUDqJ#AsI2r1673UplhdQx6VZRQFc08MTrcOGNcf-e7AOzUtM aCapitulo_062.mp4
    - mega-get https://mega.nz/file/w7J2CbrL#-S5CguZVJVYZre0Xvy9khxJ9O4XldS2QRKr8kY9-E5s aCapitulo_062.srt
    - ffmpeg -i aCapitulo_062.mp4 -i aCapitulo_062.srt -c copy -c:s mov_text Capitulo_062.mp4
    - travis_wait 20 curl -T Capitulo_062.mp4 https://transfer.sh/Capitulo_062.mp4
    - mega-get https://mega.nz/file/ozJylbxB#bmPWmrNI48OxRIN-O76LRuETDVmfOnlCI48LWn0yeg0 aCapitulo_063.mp4
    - mega-get https://mega.nz/file/pmIwjR4Q#fTUgUnJWOGw2QmJ6FKPwT_mdsRBcGccSPj6gBDe0k7o aCapitulo_063.srt
    - ffmpeg -i aCapitulo_063.mp4 -i aCapitulo_063.srt -c copy -c:s mov_text Capitulo_063.mp4
    - travis_wait 20 curl -T Capitulo_063.mp4 https://transfer.sh/Capitulo_063.mp4
    - mega-get https://mega.nz/file/5uIGyZwJ#wrTSqmqvHNbuKZ3w5JYKV4WYTd4NM3l6oN3mCErsgE0 aCapitulo_064.mp4
    - mega-get https://mega.nz/file/FrYEhBxb#5HEbjSOYpzXu1Y5SRNbcpUcYHjGuyQX2vH4GMpt24Io aCapitulo_064.srt
    - ffmpeg -i aCapitulo_064.mp4 -i aCapitulo_064.srt -c copy -c:s mov_text Capitulo_064.mp4
    - travis_wait 20 curl -T Capitulo_064.mp4 https://transfer.sh/Capitulo_064.mp4
    - mega-get https://mega.nz/file/1qRGkZgY#5t_RJ2psTEFR227BUpDkZz96OUunuJ3RZyE4vWk3W-4 aCapitulo_065.mp4
    - mega-get https://mega.nz/file/MiREwRRA#QmhdvOo6IhIKAUN1mfc75mZnKh4UKRmx_XMKPcnI2To aCapitulo_065.srt
    - ffmpeg -i aCapitulo_065.mp4 -i aCapitulo_065.srt -c copy -c:s mov_text Capitulo_065.mp4
    - travis_wait 20 curl -T Capitulo_065.mp4 https://transfer.sh/Capitulo_065.mp4
    - mega-get https://mega.nz/file/szYQWbxQ#gJKejSYa603lggj2heIe02LAmiOSw0EOLKP26FnAffs aCapitulo_066.mp4
    - mega-get https://mega.nz/file/YnQ2HLZD#c_qhHnb4XcPuaMl6cciWB1DnKOS8sTwr0e5jtPjsUN8 aCapitulo_066.srt
    - ffmpeg -i aCapitulo_066.mp4 -i aCapitulo_066.srt -c copy -c:s mov_text Capitulo_066.mp4
    - travis_wait 20 curl -T Capitulo_066.mp4 https://transfer.sh/Capitulo_066.mp4
    - mega-get https://mega.nz/file/tvZkhLLC#3XQymspB_GNSnGwcErPEKNuh13cPIU5ck7aHkYoO40o aCapitulo_067.mp4
    - mega-get https://mega.nz/file/kqJygBJC#NTU2PyRgtUhUEP-sLEFl-M5LYkaMcytgxIA95JhHjik aCapitulo_067.srt
    - ffmpeg -i aCapitulo_067.mp4 -i aCapitulo_067.srt -c copy -c:s mov_text Capitulo_067.mp4
    - travis_wait 20 curl -T Capitulo_067.mp4 https://transfer.sh/Capitulo_067.mp4
    - mega-get https://mega.nz/file/tyQSCZDJ#ZXK1cVUjj20Jhpl1U9cG5oeZx12ZU_OBZh220Td_uW4 aCapitulo_068.mp4
    - mega-get https://mega.nz/file/lqQSlDZa#pjoSV4UdcH4A0Hjuyfn1M8-5xrfypYJBqvvY8JnYp6I aCapitulo_068.srt
    - ffmpeg -i aCapitulo_068.mp4 -i aCapitulo_068.srt -c copy -c:s mov_text Capitulo_068.mp4
    - travis_wait 20 curl -T Capitulo_068.mp4 https://transfer.sh/Capitulo_068.mp4
